#!/bin/sh
case "$1" in
  start)
    /usr/bin/aesdsocket -d
    ;;
  stop)
    pkill aesdsocket || true
    ;;
  restart|reload)
    "$0" stop
    sleep 1
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
